baseURL = 'https://example.github.io/blog-site'
languageCode = 'en-us'
title = 'My Blog'
theme = 'PaperMod'

[params]
  author = "Your Name"
  description = "A simple blog built with Hugo"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

[params.homeInfoParams]
  Title = "Welcome to My Blog"
  Content = "A place where I share my thoughts and experiences"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/[your-username]"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30
